### ISSUE TITLE
Bower error: Package retext-keywords not found

### ISSUE THREAD

**Issue by franciskim** [wooorm/retext#22]
When running ```bower install retext-keywords```, I get the error ```ENOTFOUND Package retext-keywords not found```. I would also appreciate some help on getting retext-keywords running on the client-side as per the demo.

**Comment by wooorm** [comment]
It seems i’ve forgotten to publish to bower. I just did, so you should be able to download retext-keywords from the registry.

However, as bower is just a package manager, you still need to combine the scripts you want (retext-keyword’s, and retext’s dependencies, and your script) into one file. I recommend using something like webpack or browserify. Script tags won’t work as `retext` and `retext-keywords` use CommonJS, thus, a build step.

To do that, I recommend using duo:

```bash
git clone git@github.com:wooorm/retext-keywords.git
cd retext-keywords
git checkout gh-pages
duo --stdout index.js > build.js
```

And then just open the `index.html` file in a browser.

**Comment by franciskim** [comment]
Thank you @wooorm - will give it a shot. Love the work you've done.

**Comment by franciskim** [comment]
Your steps explain everything I needed to know - thanks again.

**Comment by wooorm** [comment]
Great to hear :) Just create a PR or e-mail me if you’ve got more questions!
