### ISSUE TITLE
Code block inside list not properly displayed

### ISSUE THREAD

**Issue by andrewbenton** [wooorm/retext#26]
Code blocks nested inside lists do not properly display in the preview window.

Version: 5.0.2
OS: Fedora 22

Example:
```markdown
1. asdf

2. jkl;

    ```bash
    echo "line 1"
    echo "line 2"
    ```

3. aeio
```

Produces:

> 1. asdf
> 2. jkl;
> 
>     bash echo "line1" echo "line 2"
> 3. aeio

**Comment by wooorm** [comment]
I think your issue is related to a different retext: <http://lmgtfy.com/?q=retext>.

**Comment by andrewbenton** [comment]
You're absolutely right.  Sorry about that!
