### ISSUE TITLE
Cannot store function in variable.

### ISSUE THREAD

**Issue by FranzSkuffka** [wooorm/retext#29]
The following code executes as expected, reporting issues of the given text.
```
                retext().use(readability).process(processedReview.text, function (err, file) {
                        console.log(report(file));
                });
```
However this one reports 'no issues found' for the exact same text. Am I missing some JS basics here? ATM  I am  really  stuck, thank you for your help.
```
                var process = retext().use(readability).process;
                process(processedReview.text, function (err, file) {
                        console.log(report(file));
                });
```

**Comment by wooorm** [comment]
Yes, as you found out, invoking 'process' without a context object does not work. Use [bind](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind) if you'd want to bind a context object to the process function.

**Comment by FranzSkuffka** [comment]
Great, thank you for debugging my code :sob:

**Comment by wooorm** [comment]
No problem! :wink:

**Comment by FranzSkuffka** [comment]
Different question, why did you choose to execute a callback synchronously instead of a return value for the `process` method?

**Comment by wooorm** [comment]
The callback is sync when it can be, and async if it needs to be, sometimes syncness is easier!

**Comment by FranzSkuffka** [comment]
I had trouble promisifying this. I need run a few retext processes on a target text and then store all the results in an object

**Comment by wooorm** [comment]
I have no idea what your code is like, so I cannot comment on that.

**Comment by FranzSkuffka** [comment]
Line 95 - It prints completely empty reports.
https://github.com/FranzSkuffka/amazon-review-analyzer/blob/promisification/app.js

I have worked with promises and promisification before but I cannot figure out how to apply it to retext. Maybe you have a working example somewhere.

Will contribute to docs once i figured this out :)

**Comment by wooorm** [comment]
Seems Bluebird’d promisify support functions, not methods. See its section on methods [here](http://bluebirdjs.com/docs/api/promise.promisify.html).

**Comment by FranzSkuffka** [comment]
I will try writing my own promise then. Thanks!

**Comment by FranzSkuffka** [comment]
Ok I think I just got this. Will contribute soon. Thanks for the support.
