### ISSUE TITLE
Any  retext classify plugins out there?

### ISSUE THREAD

**Issue by s-a** [wooorm/retext#34]
I try to find a natural language classify module and wonder if there is no one out there for retext so far.
I wish I could do something like this ...  

```
speak.classify("What is your name?")             //=> { action: "what", owner: "listener", subject: "name" }
speak.classify("Do you know what time it is?")   //=> { action: "what", owner: "it", subject: "time" }
```

**Comment by wooorm** [comment]
Nope, not yet! It’s pretty hard to do actually, but it would be cool :)
