### ISSUE TITLE
Feature request: POS (part of speech) tagging

### ISSUE THREAD

**Issue by dbkaplun** [wooorm/retext#44]

**Comment by wooorm** [comment]
There a plug-in for that: [retext-pos](https://github.com/wooorm/retext-pos).

**Comment by dbkaplun** [comment]
Sorry, I meant [dependency parsing](https://en.wikipedia.org/wiki/Dependency_grammar). I'll update the title.

**Comment by wooorm** [comment]
You can use retext-pos for that. The dependency parsing should go in a new plug-in. I have no experience with that though, so I cannot be of much help.

**Comment by dbkaplun** [comment]
OK, I could imagine it's similar to a regular expression/finite state machine around parts of speech of a sentence rather than characters of a string. I guess I will have to look elsewhere as I have no experience with dependency parsing either, just a basic understanding.
