### ISSUE TITLE
Example/demos to help with integration

### ISSUE THREAD

**Issue by oyeanuj** [wooorm/retext#46]
Hi @wooorm, firstly, thank you for open sourcing this project!

I'm very excited to be able to integrate it with a web-editor, ideally, on the client-side itself. But looking through the documentation, I couldn't find a link to a demo or an example app that uses this. Is there a link somewhere, that I might have just missed? It would be very useful to be able to play with it and have an example of a possible integration.

Thank you!

**Comment by wooorm** [comment]
Hi @oyeanuj 👋 

Have you seen the example [linked to in the readme](https://github.com/wooorm/retext/tree/master/packages/retext#usage)? Also, some of the plugins have demo’s, such as [retext-sentiment](http://wooorm.com/retext-sentiment/) and [retext-pos](http://wooorm.com/retext-pos/), on their gh-pages branches.

Cheers

**Comment by oyeanuj** [comment]
Ah, I missed the GH Pages branch on the plugins. My bad - thank you for the quick response! 

I was mainly curious if this would work in a browser environment instead of node, and it seems like it does. I'll explore more.

Thank you!
