### ISSUE TITLE
No release notes for 5.0.0?

### ISSUE THREAD

**Issue by jescalan** [wooorm/retext#50]
I can't find them in the releases or in `history.md`, yet my tests are failing after the upgrade. Where might I be able to find release notes?

**Comment by wooorm** [comment]
Sorry about that, thanks for asking. It’s been rather busy upgrading the whole ecosystem.

Nothing much changed in retext itself, but unified (the underlying interface) received quite some changes. You can find more on that on the [Releases page](https://github.com/wooorm/retext/releases/tag/5.0.0).
