### ISSUE TITLE
Small typo in doc/plugins.md

### ISSUE THREAD

**Issue by lurch** [wooorm/retext#51]
https://github.com/wooorm/retext/blob/master/doc/plugins.md#list-of-utilities says

> And finally, see wooorm/vfile for a list of utilities for working with virtual files and

Looks like something is missing after the final `and`?

**Comment by wooorm** [comment]
Yeah, it should be `with virtual files.`, could you create a PR?

**Comment by lurch** [comment]
Done: #52
